// Complete Structured Catalog of Matt Pocock's Skills
window.SKILLS_DATA = [
  // 01 需求对齐 (Alignment)
  {
    id: 'grill-me',
    name: 'grill-me',
    stage: 'alignment',
    stageZh: '01 需求对齐',
    category: 'productivity',
    categoryZh: '效率工具',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '就一个计划或设计对你进行持续盘问（Grilling），直到设计树的每个分支都被完全解决。',
    longDesc: '在非代码或早期产品构思阶段，让 AI 扮演挑剔的资深架构师，连续追问你遗漏的假设、边界情况与潜在风险。',
    exampleCmd: '/grill-me',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/productivity/grill-me/SKILL.md',
    tags: ['需求对齐', '边界盘问', '思维收敛']
  },
  {
    id: 'grill-with-docs',
    name: 'grill-with-docs',
    stage: 'alignment',
    stageZh: '01 需求对齐 & 领域建模',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '严拷式会话，同时构建项目的领域模型，打磨术语并就地更新 CONTEXT.md 和 ADR。',
    longDesc: '在动手编码前与 Agent 彻底达成共识。通过连续高密度的提问挖掘边界条件，并在项目中自动建立通用语言与架构决策记录（ADR），彻底消灭返工。',
    exampleCmd: '/grill-with-docs',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/grill-with-docs/SKILL.md',
    tags: ['核心王牌', '领域建模', 'ADR记录', '严拷会话']
  },
  {
    id: 'to-questionnaire',
    name: 'to-questionnaire',
    stage: 'alignment',
    stageZh: '01 需求对齐',
    category: 'productivity',
    categoryZh: '效率工具',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '把无法独立决定的事情，转成一份 Markdown 问卷发给唯一能作答的决策人。',
    longDesc: '将技术卡点转为高效的异步协作问卷。明确列出选项优劣、影响范围和推荐值，让产品经理或业务负责人快速做出定夺。',
    exampleCmd: '/to-questionnaire',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/productivity/to-questionnaire/SKILL.md',
    tags: ['决策问卷', '异步沟通', '跨角色对齐']
  },
  {
    id: 'ask-matt',
    name: 'ask-matt',
    stage: 'alignment',
    stageZh: '01 需求对齐',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '询问哪个技能或流程适合你当下的处境。本仓库用户调用技能之上的顶级路由器。',
    longDesc: '不知道当前开发场景应该用哪个技能？运行 /ask-matt，AI 将分析你当前的任务状态、分支或困惑，自动为你指引最合适的技能与下一步工程行动。',
    exampleCmd: '/ask-matt',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/ask-matt/SKILL.md',
    tags: ['工作流路由', '导航分发', '技能指引']
  },

  // 02 领域建模 (Domain Modeling)
  {
    id: 'domain-modeling',
    name: 'domain-modeling',
    stage: 'modeling',
    stageZh: '02 领域建模',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '主动构建并打磨项目的领域模型——挑战术语、边界压测，更新 CONTEXT.md 与 ADR。',
    longDesc: '领域驱动设计（DDD）实践核心。让 Agent 审查项目核心概念，消除歧义词汇，并在代码库根目录维护精确的通用语言字典。',
    exampleCmd: '由 Agent 自动调用',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/domain-modeling/SKILL.md',
    tags: ['通用语言', 'DDD', 'CONTEXT.md']
  },
  {
    id: 'wait-what',
    name: 'wait-what',
    stage: 'modeling',
    stageZh: '02 领域建模',
    category: 'productivity',
    categoryZh: '效率工具',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '一旦某条消息没听懂立刻触发。Agent 会结合上下文并用通俗大白话重新讲解。',
    longDesc: '当 Agent 抛出一堆晦涩术语让你一头雾水时，输入 /wait-what，Agent 会立即踩刹车，引用 CONTEXT.md 词汇用平实易懂的比喻重新拆解。',
    exampleCmd: '/wait-what',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/productivity/wait-what/SKILL.md',
    tags: ['大白话拆解', '术语澄清', '降低认知负荷']
  },
  {
    id: 'writing-for-agents',
    name: 'writing-for-agents',
    stage: 'modeling',
    stageZh: '02 领域建模',
    category: 'productivity',
    categoryZh: '效率工具',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '为 Agent 写文档的黄金准则：编写技能、AGENTS.md、CLAUDE.md 及指针文档。',
    longDesc: '专为大语言模型优化的文档编写方法论。避免人类官僚式废话，用结构化标记、强类型规则与反例指引，让 AI 理解精度提升数倍。',
    exampleCmd: '由 Agent 自动调用',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/productivity/writing-for-agents/SKILL.md',
    tags: ['AGENTS.md', '提示词工程', '结构化指引']
  },

  // 03 规格与拆解 (Spec & Breakdown)
  {
    id: 'to-spec',
    name: 'to-spec',
    stage: 'spec',
    stageZh: '03 规格与工单',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '把当前对话转成一份规格说明，并发布到问题追踪器。无需二次访谈，直接提炼沉淀。',
    longDesc: '将即兴讨论与脑暴对话智能提炼为结构化规格说明（Spec）。在生成前还会严谨提示你正在触碰哪些模块，为后续实施奠定清晰契约。',
    exampleCmd: '/to-spec',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/to-spec/SKILL.md',
    tags: ['规格提炼', '需求文档', '模块边界检查']
  },
  {
    id: 'to-tickets',
    name: 'to-tickets',
    stage: 'spec',
    stageZh: '03 规格与工单',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '把计划或规格拆成一组「追踪子弹」式工单，每张都声明自己的阻塞边界与依赖关系。',
    longDesc: '将庞大的大任务拆解为小而可验证的垂直切片工单（Tracer Bullet Tickets），在本地或远程追踪器上清晰标识先后依赖，让 Agent 按序突破。',
    exampleCmd: '/to-tickets',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/to-tickets/SKILL.md',
    tags: ['追踪子弹', '工单拆解', '依赖图谱']
  },
  {
    id: 'triage',
    name: 'triage',
    stage: 'spec',
    stageZh: '03 规格与工单',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '让问题工单通过一组由分类角色构成的有限状态机流转。',
    longDesc: '以严谨的状态机角色流转机制，对 GitHub / Linear 或本地工单进行分类、加标、优先级定级与准备度检查，确保进入开发阶段的任务定义清晰无歧义。',
    exampleCmd: '/triage',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/triage/SKILL.md',
    tags: ['工单分类', '状态机', '优先级评估']
  },
  {
    id: 'wayfinder',
    name: 'wayfinder',
    stage: 'spec',
    stageZh: '03 规格与工单',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '把远超单个会话的大任务，规划成追踪器上一张共享的决策工单地图。',
    longDesc: '针对复杂史诗级重构或跨系统特性的领航员。建立由决策节点和探索工单构成的动态地图，逐一消除未知，直到通往目的地的路径完全清晰。',
    exampleCmd: '/wayfinder',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/wayfinder/SKILL.md',
    tags: ['复杂任务规划', '决策地图', '史诗任务']
  },

  // 04 测试驱动编码 (TDD & Implementation)
  {
    id: 'tdd',
    name: 'tdd',
    stage: 'tdd',
    stageZh: '04 TDD红绿实现',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '测试驱动开发，严格采用红-绿-重构循环。以垂直切片方式构建功能或修 bug。',
    longDesc: '让 Agent 不再盲飞。提供极高质量的测试规范指引，坚决执行 Red（先写挂掉的测试）-> Green（最小代码跑通）-> Refactor（保持绿灯下重构）。',
    exampleCmd: '由 Agent 自动调用或通过 /tdd 触发',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/tdd/SKILL.md',
    tags: ['红绿重构', 'TDD先行', '高质量代码']
  },
  {
    id: 'implement',
    name: 'implement',
    stage: 'tdd',
    stageZh: '04 TDD红绿实现',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '构建由规格或工单描述的工作，在接缝处驱动 /tdd，并在提交前以 /code-review 收尾。',
    longDesc: '完整的闭环交付引擎。从读取工单开始，在模块边界驱动测试先行（TDD），实现业务逻辑，并在最终 git commit 之前执行双轴代码审查。',
    exampleCmd: '/implement',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/implement/SKILL.md',
    tags: ['闭环交付', 'TDD驱动', '审查收尾']
  },
  {
    id: 'prototype',
    name: 'prototype',
    stage: 'tdd',
    stageZh: '04 TDD红绿实现',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '构建一次性原型来回答设计问题——单文件 HTML 或多种可切换 UI 变体。',
    longDesc: '快速验证逻辑状态机或 UI 交互假说。在投入正式编码前，生成可直接在浏览器中交互的纯 HTML 探针，低成本消除设计风险。',
    exampleCmd: '由 Agent 自动调用或通过 /prototype 触发',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/prototype/SKILL.md',
    tags: ['原型验证', 'UI探针', '低成本试错']
  },
  {
    id: 'diagnosing-bugs',
    name: 'diagnosing-bugs',
    stage: 'tdd',
    stageZh: '04 TDD红绿实现',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '针对疑难 bug 和性能回退的严谨诊断循环：变红反馈回路 → 最小化 → 假设 → 插桩 → 修复 → 回归测试。',
    longDesc: '彻底告别盲目瞎猜式 debug。强制 Agent 按照科学实验流程：首先构造必现的失败测试，精简复现路径，提出假说并通过日志插桩验证，最后修复并做回归验证。',
    exampleCmd: '由 Agent 自动调用或通过 /diagnosing-bugs 触发',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/diagnosing-bugs/SKILL.md',
    tags: ['科学调试', '必现测试', '探针日志']
  },

  // 05 审查与合并 (Review & Merge)
  {
    id: 'code-review',
    name: 'code-review',
    stage: 'review',
    stageZh: '05 双轴代码审查',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '对变更执行双轴并行审查：标准（编码规范与代码坏味道）与规格（是否忠实满足需求）。',
    longDesc: '启动两个独立的并行子 Agent 分别进行审查：一个只关注代码风格、Fowler 坏味道与质量基线，另一个只比对原始 Spec 验证逻辑完整性，互不干扰污染。',
    exampleCmd: '由 Agent 自动调用或通过 /code-review 触发',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/code-review/SKILL.md',
    tags: ['双轴审查', '编码规范', '规格忠实度']
  },
  {
    id: 'resolving-merge-conflicts',
    name: 'resolving-merge-conflicts',
    stage: 'review',
    stageZh: '05 双轴代码审查',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '逐块解决 Git merge/rebase 冲突，追溯各方一手意图，绝不 --abort。',
    longDesc: '结构化冲突解决指引。不仅比对代码冲突标记，更通过 git log 追溯双方提交者的原始设计意图，完成高质量合并，绝不暴力覆盖或盲目放弃。',
    exampleCmd: '由 Agent 自动调用',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/resolving-merge-conflicts/SKILL.md',
    tags: ['Git冲突', '意图追溯', '安全合并']
  },

  // 06 架构演进与深模块 (Architecture & Deepening)
  {
    id: 'improve-codebase-architecture',
    name: 'improve-codebase-architecture',
    stage: 'deepening',
    stageZh: '06 架构演进',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '扫描代码库以寻找「加深 (Deepening)」机会，以可视化 HTML 报告呈现，并就选中项逐一严拷。',
    longDesc: '定期运行的架构诊断雷达。依据《软件设计的哲学》理念，寻找浅模块与高耦合点，提供深模块重构方案与可视化 HTML 架构体检报告。',
    exampleCmd: '/improve-codebase-architecture',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/improve-codebase-architecture/SKILL.md',
    tags: ['深模块', '架构扫描', '反代码熵增']
  },
  {
    id: 'codebase-design',
    name: 'codebase-design',
    stage: 'deepening',
    stageZh: '06 架构演进',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '设计深模块（deep modules）的共享纪律：大量行为藏在小接口之后，接缝干净。',
    longDesc: '基于 John Ousterhout《软件设计的哲学》。指导 Agent 避免创建过多的浅封装类和贫血模型，设计内聚而深厚的软件模块与接口。',
    exampleCmd: '由 Agent 自动调用',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/codebase-design/SKILL.md',
    tags: ['深模块设计', '接口精简', '内聚度']
  },

  // Other Helper Skills
  {
    id: 'setup-matt-pocock-skills',
    name: 'setup-matt-pocock-skills',
    stage: 'spec',
    stageZh: '初始化配置',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '为当前仓库配置工程技能（问题追踪器、分类标签、领域文档布局）。每个仓库运行一次。',
    longDesc: '工程技能套件的初始化向导。配置 GitHub/Linear 连接方式、工单分类标签规范以及 CONTEXT.md 文档存放目录，是让全套技能协同运作的基石。',
    exampleCmd: '/setup-matt-pocock-skills',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/setup-matt-pocock-skills/SKILL.md',
    tags: ['必备初始化', '仓库配置']
  },
  {
    id: 'research',
    name: 'research',
    stage: 'modeling',
    stageZh: '一手调研',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '针对高可信一手来源调研问题，并将结论以带引用的 Markdown 记录到仓库中（后台运行）。',
    longDesc: '防止 AI 幻觉与二手过时信息。指导 Agent 检索官方文档、源码实现与一手权威资料，生成带精确引注的研究报告。',
    exampleCmd: '由 Agent 自动调用或通过 /research 触发',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/research/SKILL.md',
    tags: ['一手调研', '官方文档检索', '防幻觉']
  },
  {
    id: 'handoff',
    name: 'handoff',
    stage: 'spec',
    stageZh: '会话接力',
    category: 'productivity',
    categoryZh: '效率工具',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '把当前对话状态压缩成一份精炼的交接文档，以便另一个 Agent 或会话无缝接力。',
    longDesc: '解决长会话上下文超载（Context Overflow）利器。提取关键已完成事项、未决问题和环境变量，生成即插即用的交接胶囊。',
    exampleCmd: '/handoff',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/productivity/handoff/SKILL.md',
    tags: ['上下文压缩', '会话交接']
  },
  {
    id: 'teach',
    name: 'teach',
    stage: 'alignment',
    stageZh: '交互教学',
    category: 'productivity',
    categoryZh: '效率工具',
    type: 'user',
    typeZh: '用户调用 (编排)',
    desc: '在多个会话中教你一项新技能或概念，以当前目录作为一个有状态的教学工作区。',
    longDesc: '交互式苏格拉底教学法。在当前目录生成演练文件和小测验，边写边测，带你系统掌握新技术栈或框架内幕。',
    exampleCmd: '/teach <主题>',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/productivity/teach/SKILL.md',
    tags: ['苏格拉底教学', '有状态工作区']
  },
  {
    id: 'wizard',
    name: 'wizard',
    stage: 'tdd',
    stageZh: '向导脚本',
    category: 'engineering',
    categoryZh: '工程实践',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '生成交互式 bash 向导，引导人类完成只有人类能做的基础设施配置、密钥录入或迁移。',
    longDesc: '当遇到需要登录云控制台、获取 OAuth Token 或手动授权的场景时，Agent 自动生成色彩鲜明、带进度保存和校验的交互式脚本，协助开发者轻松通关。',
    exampleCmd: '由 Agent 自动调用',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/engineering/wizard/SKILL.md',
    tags: ['Bash向导', '自动化脚本', '人工运维']
  },
  {
    id: 'grilling',
    name: 'grilling',
    stage: 'alignment',
    stageZh: '底层原语',
    category: 'productivity',
    categoryZh: '效率工具',
    type: 'model',
    typeZh: '模型调用 (纪律)',
    desc: '就计划、决策或想法对用户进行持续盘问的底层访谈原语。',
    longDesc: 'grill-me, grill-with-docs, triage 等高级技能背后的通用访谈算法引擎。控制提问节奏、收敛分支并防止话题漂移。',
    exampleCmd: '由高级技能内部调用',
    githubUrl: 'https://github.com/mattpocock/skills/blob/main/skills/productivity/grilling/SKILL.md',
    tags: ['访谈原语', '算法核心']
  }
];
